version: '3.8'
services:
  app:
    build: .
    container_name: tomcat-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=your_user
      - DB_PASSWORD=your_password
      - DB_NAME=your_database

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local

